### ISSUE TITLE
Bug with xformers 0.0.30 memory_efficient_attention on 5090 with half precision, torch 2.7, cuda 12.8

### ISSUE THREAD

**Issue by cdancette** [facebookresearch/xformers#1251]
# 🐛 Bug

I am encountering an error with xformers 0.0.30 memory_efficient_attention on RTX 5090, with half-precision tensors. I am using torch 2.7 with cuda 12.8.

Calling the function returns the following error:
```
CUDA error (/__w/xformers/xformers/third_party/flash-attention/hopper/flash_fwd_launch_template.h:175): no kernel image is available for execution on the device
```

Note that it works in full precision.

Also, I tried installing the latest version from source  (commit 8fc8ec5a4d6498ff81c0c418b89bbaf133ae3a44), and I cannot reproduce the issue.

## Command to reproduce

```
from xformers.ops import memory_efficient_attention
import torch
q, k, v = torch.randn(5, 10, 128).half().cuda(), torch.randn(5, 10, 128).half().cuda(), torch.randn(5, 10, 128).half().cuda()
memory_efficient_attention(q, k, v)
```

Returns 
```
CUDA error (/__w/xformers/xformers/third_party/flash-attention/hopper/flash_fwd_launch_template.h:175): no kernel image is available for execution on the device
```

## Environment

You can run the script with:

- PyTorch Version (e.g., 1.0): 2.7
- OS (e.g., Linux): ubuntu 24.04.2
- How you installed PyTorch (`conda`, `pip`, source): poetry/pip
- Build command you used (if compiling from source):
- Python version: 3.12
- CUDA/cuDNN version: 12.8
- GPU models and configuration: RTX 5090
- Any other relevant information:

**Comment by Cupcee** [comment]
I have same issue

**Comment by silvertuanzi** [comment]
xformers 0.0.30 isn't compatible with RTX50 series. The maintainers forgot to add 10.0 (datacenter B series) and 12.0 (RTX 50 series) in `TORCH_CUDA_ARCH_LIST`.

**Comment by mihkhub** [comment]
I have same issue:

```
==((====))==  Unsloth 2025.4.7: Fast Qwen3 patching. Transformers: 4.51.3.
   \\   /|    NVIDIA GeForce RTX 5090. Num GPUs = 2. Max memory: 31.345 GB. Platform: Linux.
O^O/ \_/ \    Torch: 2.7.0+cu128. CUDA: 12.0. CUDA Toolkit: 12.8. Triton: 3.3.0
\        /    Bfloat16 = TRUE. FA [Xformers = 0.0.30. FA2 = False]
 "-____-"     Free license: http://github.com/unslothai/unsloth


==((====))==  Unsloth - 2x faster free finetuning | Num GPUs used = 1
   \\   /|    Num examples = 24,065 | Num Epochs = 1 | Total steps = 30
O^O/ \_/ \    Batch size per device = 4 | Gradient accumulation steps = 4
\        /    Data Parallel GPUs = 1 | Total batch size (4 x 4 x 1) = 16
 "-____-"     Trainable parameters = 128,450,560/14,000,000,000 (0.92% trained)
  0%|                                                                                                  | 0/30 [00:00<?, ?it/s]CUDA error (/__w/xformers/xformers/third_party/flash-attention/hopper/flash_fwd_launch_template.h:175): no kernel image is available for execution on the device

```

**Comment by lw** [comment]
Uhm, it's indeed likely that we didn't build kernels for the 10.0 and 12.0 compute capabilities.

On the other hand, I don't think this should be necessary, as CUDA should be able to use the kernels built for earlier capabilities. This might lead to poorer performance but, since Flash hasn't yet been updated for Blackwell, it shouldn't matter.

We'll need to look into it more closely.

**Comment by kelvin-homann** [comment]
Unfortunately i can reproduce the error when i build the latest version. You mention the commit 8fc8ec5 works for you, well in my case it also throws an error. At least when i use it with unsloth. 

![Image](https://github.com/user-attachments/assets/d6a7ec40-50c1-49e1-9146-c3799a6173ef)

I have build a Dockerfile to run unsloth in a jupyter environment. I have taken inspiration from [here](https://github.com/spotemkin/blackwell_cuda12.8_pytorch2.8.0_py3.10_ubuntu22.04/blob/main/Dockerfile)
```Dockerfile
# Base image with CUDA 12.8 for NVIDIA Blackwell architecture (sm_120) support
FROM nvidia/cuda:12.8.0-devel-ubuntu22.04

# Labels for better container identification
LABEL description="CUDA 12.8 + PyTorch + xformers with NVIDIA Blackwell architecture (sm_120) support for RTX 5090"
LABEL version="1.0"
LABEL cuda_version="12.8.0"
LABEL ubuntu_version="22.04"
LABEL architecture="Blackwell (sm_120)"

# Environment variables
ENV DEBIAN_FRONTEND=noninteractive
ENV PYTHONUNBUFFERED=1
ENV PATH="/usr/local/cuda/bin:${PATH}"
ENV LD_LIBRARY_PATH="/usr/local/cuda/lib64:${LD_LIBRARY_PATH}"
ENV TORCH_CUDA_ARCH_LIST="12.0"

# Install basic dependencies
RUN apt-get update && apt-get install -y --no-install-recommends \
    python3 \
    python3-pip \
    python3-dev \
    python3-venv \
    git \
    wget \
    ninja-build \
    cmake \
    build-essential \
    ca-certificates \
    # Required for OpenCV
    libgl1-mesa-glx \
    libglib2.0-0 \
    libsm6 \
    libxext6 \
    libxrender-dev \
    # Cleanup apt cache to reduce image size
    && apt-get clean \
    && rm -rf /var/lib/apt/lists/* \
    # Create symlinks for Python
    && ln -sf /usr/bin/python3 /usr/bin/python \
    && ln -sf /usr/bin/pip3 /usr/bin/pip

# Upgrade pip
RUN pip install --no-cache-dir --upgrade pip setuptools wheel unsloth

# Install PyTorch ecosystem with CUDA 12.8 support (nightly for Blackwell support)
RUN pip install --no-cache-dir --pre torch torchvision torchaudio \
    --index-url https://download.pytorch.org/whl/nightly/cu128

# Install xformers from GitHub for the latest features and Blackwell support
RUN pip install --pre -v -U git+https://github.com/facebookresearch/xformers.git@main#egg=xformers

# Install commonly used deep learning libraries and utilities
RUN pip install --no-cache-dir \
    numpy \
    scipy \
    pandas \
    matplotlib \
    opencv-python \
    pillow \
    tqdm \
    transformers \
    diffusers \
    accelerate \
    safetensors \
    bitsandbytes \
    jupyter \
    notebook

# Create a workspace directory
WORKDIR /workspace

# Add verification script
COPY verify_blackwell.py /usr/local/bin/verify_blackwell.py
RUN chmod +x /usr/local/bin/verify_blackwell.py

EXPOSE 8888

# Create entrypoint script
RUN echo '#!/bin/bash\necho "=== NVIDIA Blackwell Docker Container ==="\necho "CUDA 12.8 + PyTorch + xformers with sm_120 support"\necho "Run \"python /usr/local/bin/verify_blackwell.py\" to verify GPU support"\nexec "$@"' > /entrypoint.sh \
    && chmod +x /entrypoint.sh

ENTRYPOINT ["/entrypoint.sh"]
CMD ["jupyter", "notebook", "--ip=0.0.0.0", "--allow-root", "--NotebookApp.token=''", "--NotebookApp.password=''", "--NotebookApp.allow_origin='*'"]
```

When i run the mentioned verify_blackwell.py script it outputs the following: 
```log
======================================================================
 NVIDIA BLACKWELL SUPPORT VERIFICATION TOOL
======================================================================
Date: 2025-05-12 11:43:50
Python: 3.10.12 (/usr/bin/python)

PyTorch: 2.8.0.dev20250511+cu128
CUDA available: True
CUDA version: 12.8
Supported CUDA architectures: sm_75 sm_80 sm_86 sm_90 sm_100 sm_120 compute_120

✅ Blackwell architecture (sm_120) is supported by PyTorch!

GPU count: 1

GPU #0: NVIDIA GeForce RTX 5080
  Compute capability: 12.0
  Memory: 15.92 GB
  ✅ This is a Blackwell architecture GPU!

xformers: 0.0.31+8fc8ec5.d20250512

Xformers feature status:
  memory_efficient_attention.ckF                     unavailable
  memory_efficient_attention.ckB                     unavailable
  memory_efficient_attention.ck_decoderF             unavailable
  memory_efficient_attention.ck_splitKF              unavailable
  memory_efficient_attention.cutlassF-pt             available
  memory_efficient_attention.cutlassB-pt             available
  memory_efficient_attention.fa2F@2.5.7-pt           available
  memory_efficient_attention.fa2B@2.5.7-pt           available
  memory_efficient_attention.fa3F@0.0.0              unavailable
  memory_efficient_attention.fa3B@0.0.0              unavailable
  memory_efficient_attention.triton_splitKF          available
  indexing.scaled_index_addF                         available
  indexing.scaled_index_addB                         available
  indexing.index_select                              available
  sp24.sparse24_sparsify_both_ways                   available
  sp24.sparse24_apply                                available
  sp24.sparse24_apply_dense_output                   available
  sp24._sparse24_gemm                                available
  sp24._cslt_sparse_mm_search@0.6.3                  available
  sp24._cslt_sparse_mm@0.6.3                         available
  swiglu.dual_gemm_silu                              available
  swiglu.gemm_fused_operand_sum                      available
  swiglu.fused.p.cpp                                 available
  is_triton_available                                True

❌ The following xformers features are unavailable:
   - memory_efficient_attention.ckF
   - memory_efficient_attention.ckB
   - memory_efficient_attention.ck_decoderF
   - memory_efficient_attention.ck_splitKF
   - memory_efficient_attention.fa3F@0.0.0
   - memory_efficient_attention.fa3B@0.0.0
   Please check your xformers installation or build configuration.

Running a simple GPU computation test...
✅ GPU computation successful! Result shape: torch.Size([1000, 1000])

Running nvidia-smi:
Mon May 12 11:43:52 2025       
+-----------------------------------------------------------------------------------------+
| NVIDIA-SMI 575.51.03              Driver Version: 576.28         CUDA Version: 12.9     |
|-----------------------------------------+------------------------+----------------------+
| GPU  Name                 Persistence-M | Bus-Id          Disp.A | Volatile Uncorr. ECC |
| Fan  Temp   Perf          Pwr:Usage/Cap |           Memory-Usage | GPU-Util  Compute M. |
|                                         |                        |               MIG M. |
|=========================================+========================+======================|
|   0  NVIDIA GeForce RTX 5080        On  |   00000000:01:00.0  On |                  N/A |
|  0%   40C    P0             30W /  360W |    3023MiB /  16303MiB |     11%      Default |
|                                         |                        |                  N/A |
+-----------------------------------------+------------------------+----------------------+
                                                                                         
+-----------------------------------------------------------------------------------------+
| Processes:                                                                              |
|  GPU   GI   CI              PID   Type   Process name                        GPU Memory |
|        ID   ID                                                               Usage      |
|=========================================================================================|
|    0   N/A  N/A              15      C   /python3.10                           N/A      |
+-----------------------------------------------------------------------------------------+

Verification complete.
```

**Comment by cdancette** [comment]
@kelvin-homann I'm not sure how this would impact the results, but you are using the nightly release of torch instead of the latest released version. Could you try this command instead?

`pip3 install torch torchvision torchaudio --index-url https://download.pytorch.org/whl/cu128`

**Comment by kelvin-homann** [comment]
I tried this too, i have juggled around with many combinations all day yesterday

**Comment by loscrossos** [comment]
> Uhm, it's indeed likely that we didn't build kernels for the 10.0 and 12.0 compute capabilities.
> 
> On the other hand, I don't think this should be necessary, as CUDA should be able to use the kernels built for earlier capabilities. This might lead to poorer performance but, since Flash hasn't yet been updated for Blackwell, it shouldn't matter.
> 
> We'll need to look into it more closely.

FYI: latest flashatt was updated for blackwell. :)

**Comment by mihkhub** [comment]
> I have the "no kernel image is available for execution on the device" issue:
> 
> ```
> ==((====))==  Unsloth 2025.4.7: Fast Qwen3 patching. Transformers: 4.51.3.
>    \\   /|    NVIDIA GeForce RTX 5090. Num GPUs = 2. Max memory: 31.345 GB. Platform: Linux.
> O^O/ \_/ \    Torch: 2.7.0+cu128. CUDA: 12.0. CUDA Toolkit: 12.8. Triton: 3.3.0
> \        /    Bfloat16 = TRUE. FA [Xformers = 0.0.30. FA2 = False]
>  "-____-"     Free license: http://github.com/unslothai/unsloth
> 
> 
> ==((====))==  Unsloth - 2x faster free finetuning | Num GPUs used = 1
>    \\   /|    Num examples = 24,065 | Num Epochs = 1 | Total steps = 30
> O^O/ \_/ \    Batch size per device = 4 | Gradient accumulation steps = 4
> \        /    Data Parallel GPUs = 1 | Total batch size (4 x 4 x 1) = 16
>  "-____-"     Trainable parameters = 128,450,560/14,000,000,000 (0.92% trained)
>   0%|                                                                                                  | 0/30 [00:00<?, ?it/s]CUDA error (/__w/xformers/xformers/third_party/flash-attention/hopper/flash_fwd_launch_template.h:175): no kernel image is available for execution on the device
> ```

Encounter error when using local build:
```
GPU = NVIDIA GeForce RTX 5090. Max memory = 31.345 GB.
14.066 GB of memory reserved.
==((====))==  Unsloth - 2x faster free finetuning | Num GPUs used = 1
   \\   /|    Num examples = 24,065 | Num Epochs = 1 | Total steps = 30
O^O/ \_/ \    Batch size per device = 2 | Gradient accumulation steps = 4
\        /    Data Parallel GPUs = 1 | Total batch size (2 x 4 x 1) = 8
 "-____-"     Trainable parameters = 128,450,560/14,000,000,000 (0.92% trained)
  0%|                                                                                                  | 0/30 [00:00<?, ?it/s]python3: /project/lib/Dialect/TritonGPU/Transforms/AccelerateMatmul.cpp:42: int mlir::triton::gpu::(anonymous namespace)::getMMAVersionSafe(int, DotOp): Assertion `false && "computeCapability not supported"' failed.
```

**Comment by loscrossos** [comment]
i created a PR that solves this issue.

 https://github.com/facebookresearch/xformers/pull/1254

Funny enough the current code "as is" does not support blackwell but the above code works in windows.. which should not.

**Comment by loscrossos** [comment]
So i submitted a PR to fix this issue.. #1285 

The code already supports blackwell compilation. 

Compiling your own wheel alone with ``TORCH_CUDA_ARCH_LIST=12.0` solves the issue for:


```
from xformers.ops import memory_efficient_attention
import torch
q, k, v = torch.randn(5, 10, 128).half().cuda(), torch.randn(5, 10, 128).half().cuda(), torch.randn(5, 10, 128).half().cuda()
memory_efficient_attention(q, k, v)
```


since the wheel are already being built with CudaToolkit 12.8 it is a quite small detail to add that flag. I also added 10.0 since this is supported by CTK128 too.

@lw would that be ok?

**Comment by koiker** [comment]
I was able to run with Blackwell by installing with this command:
`pip install --no-build-isolation --pre -v -U git+https://github.com/facebookresearch/xformers.git@fde5a2fb46e3f83d73e2974a4d12caf526a4203e`

**Comment by noobmaster777** [comment]
When building with this im failing and getting a 
ValueError(f"Unknown CUDA arch ({arch}) or GPU not supported")
ValueError: Unknown CUDA arch (=12.0) or GPU not supported, 
despite doing export TORCH_CUDA_ARCH_LIST="12.0"

CUDA 12.9
Python 3.12
Torch 2.7+cu128
5090
Ubuntu 24.04

pip install xformers==0.0.30+cu128 installs but isn't used, and instead uses pytorch attention. Should i rollback to CUDA 12.8? Its backwards compatible right?

> I was able to run with Blackwell by installing with this command: `pip install --no-build-isolation --pre -v -U git+https://github.com/facebookresearch/xformers.git@fde5a2fb46e3f83d73e2974a4d12caf526a4203e`

**Comment by jiangtaozh** [comment]
tried various combinations, all don't work. please xformers produce an official version to include RTX5090 blackwell support asap.

**Comment by geekWastelands** [comment]
maybe you dont need xformers, just utilize torch:
replace
`out = xformers.ops.memory_efficient_attention(q, k, v, attn_bias=None, op=self.attention_op)`
with
`out = torch.nn.functional.scaled_dot_product_attention(q, k, v)`
