### ISSUE TITLE
xformers 0.0.32 failed: invalid argument

### ISSUE THREAD

**Issue by KohakuBlueleaf** [facebookresearch/xformers#1323]
# 🐛 Bug

In windows with torch 2.8.0 + xformers 0.0.32.post2, the xformers' attention never work and keep raise `CUDA error: invalid argument`

It looks like the FA3 implementation currently not work with blackwell consumer card (sm120)?

Or this is actually expected? If so, I hope xformers can consider to have a built-in fallback mechanism to use pytorch's attention implementation for backward compatibility.

## To Reproduce
With following script:
```python
import torch
from xformers.ops import memory_efficient_attention
a = torch.randn(4, 128, 8, 64).cuda().half()
print(memory_efficient_attention(a, a, a).shape)
```

You will see:
```
CUDA error (C:/a/xformers/xformers/third_party/flash-attention/hopper\flash_fwd_launch_template.h:188): invalid argument
```

## Expected behavior
print `(4, 128, 8, 64)`

## Environment

pytorch env info:
```
>>> python -m torch.utils.collect_env
<frozen runpy>:128: RuntimeWarning: 'torch.utils.collect_env' found in sys.modules after import of package 'torch.utils', but prior to execution of 'torch.utils.collect_env'; this may result in unpredictable behaviour
Collecting environment information...
PyTorch version: 2.8.0+cu129
Is debug build: False
CUDA used to build PyTorch: 12.9
ROCM used to build PyTorch: N/A

OS: Microsoft Windows 11 專業工作站版 (10.0.26100 64 位元)
GCC version: (conda-forge gcc 15.1.0-4) 15.1.0
Clang version: 20.1.8
CMake version: version 4.1.0
Libc version: N/A

Python version: 3.13.5 | packaged by conda-forge | (main, Jun 16 2025, 08:20:19) [MSC v.1943 64 bit (AMD64)] (64-bit runtime)
Python platform: Windows-11-10.0.26100-SP0
Is CUDA available: True
CUDA runtime version: 12.9.41
CUDA_MODULE_LOADING set to: LAZY
GPU models and configuration: GPU 0: NVIDIA GeForce RTX 5060 Ti
Nvidia driver version: 581.08
cuDNN version: Could not collect
HIP runtime version: N/A
MIOpen runtime version: N/A
Is XNNPACK available: True

CPU:
Name: AMD Ryzen 9 5950X 16-Core Processor
Manufacturer: AuthenticAMD
Family: 107
Architecture: 9
ProcessorType: 3
DeviceID: CPU0
CurrentClockSpeed: 3600
MaxClockSpeed: 3600
L2CacheSize: 8192
L2CacheSpeed: None
Revision: 8450

Versions of relevant libraries:
[pip3] numpy==2.1.2
[pip3] torch==2.8.0+cu129
[pip3] torchvision==0.23.0+cu129
[pip3] triton-windows==3.4.0.post20
[conda] Could not collect
```

xformers info:
```
>>> python -m xformers.info
xFormers 0.0.32.post2
memory_efficient_attention.ckF:                    unavailable
memory_efficient_attention.ckB:                    unavailable
memory_efficient_attention.ck_splitKF:             unavailable
memory_efficient_attention.cutlassF-pt:            available
memory_efficient_attention.cutlassB-pt:            available
memory_efficient_attention.fa2F@0.0.0:             unavailable
memory_efficient_attention.fa2B@0.0.0:             unavailable
memory_efficient_attention.fa3F@2.8.0.post2-3-g3ba6f82: available
memory_efficient_attention.fa3B@2.8.0.post2-3-g3ba6f82: available
memory_efficient_attention.fa3F_splitKV@2.8.0.post2-3-g3ba6f82: available
memory_efficient_attention.triton_splitKF:         available
indexing.scaled_index_addF:                        available
indexing.scaled_index_addB:                        available
indexing.index_select:                             available
sp24.sparse24_sparsify_both_ways:                  available
sp24.sparse24_apply:                               available
sp24.sparse24_apply_dense_output:                  available
sp24._sparse24_gemm:                               available
sp24._cslt_sparse_mm_search@0.0.0:                 available
sp24._cslt_sparse_mm@0.0.0:                        available
swiglu.dual_gemm_silu:                             available
swiglu.gemm_fused_operand_sum:                     available
swiglu.fused.p.cpp:                                available
is_triton_available:                               True
pytorch.version:                                   2.8.0+cu129
pytorch.cuda:                                      available
gpu.compute_capability:                            12.0
gpu.name:                                          NVIDIA GeForce RTX 5060 Ti
dcgm_profiler:                                     unavailable
build.info:                                        available
build.cuda_version:                                1209
build.hip_version:                                 None
build.python_version:                              3.9.13
build.torch_version:                               2.8.0+cu129
build.env.TORCH_CUDA_ARCH_LIST:                    7.5 8.0+PTX 9.0a
build.env.PYTORCH_ROCM_ARCH:                       None
build.env.XFORMERS_BUILD_TYPE:                     Release
build.env.XFORMERS_ENABLE_DEBUG_ASSERTIONS:        None
build.env.NVCC_FLAGS:                              -allow-unsupported-compiler
build.env.XFORMERS_PACKAGE_FROM:                   wheel-v0.0.32.post2
build.nvcc_version:                                12.9.41
source.privacy:                                    open source
```

**Comment by matalama80td3l** [comment]
The same error. 5060ti + cu128-torch2.8.0 on linux x64

**Comment by KohakuBlueleaf** [comment]
> The same error. 5060ti + cu128-torch2.8.0 on linux x64

checked, 5090 + cu129-torch2.8.0 + linux(ubuntu-24.04) have same error, I think it means FA3 is not supporting 50-series GPU but I think we need a proper fallback or warning here so still kind of bug
(But still, I don't know if this is expected)

**Comment by matalama80td3l** [comment]
just test, compile install xformers 0.0.30 with cu128-torch2.7.0 works. And I find https://github.com/facebookresearch/xformers/issues/1272#issuecomment-3034851360 maybe this helps too

**Comment by KohakuBlueleaf** [comment]
> just test, compile install xformers 0.0.30 with cu128-torch2.7.0 works. And I find [#1272 (comment)](https://github.com/facebookresearch/xformers/issues/1272#issuecomment-3034851360) maybe this helps too

yes the problem is about 0.0.32 not 0.0.30 or 0.0.31
also, this problem is not related to 1272 as the required pyd all exist

**Comment by KohakuBlueleaf** [comment]
> just test, compile install xformers 0.0.30 with cu128-torch2.7.0 works. And I find [#1272 (comment)](https://github.com/facebookresearch/xformers/issues/1272#issuecomment-3034851360) maybe this helps too

Another thing is xformers failed on linux as well so here are something make whole sm120 build broken, not just windows specific issue.

**Comment by Vanlams** [comment]
降级0.0.31可以解决报错问题,    python.exe -m pip install --no-deps xformers==0.0.31

**Comment by fuzhao119** [comment]
It seems you are using CUDA 12.9, so you need to install CUDA 12.9 and the corresponding toolkit on your system. After installation, run the following command (which covers almost all GPU architectures) to compile xformers from source:

**Comment by fuzhao119** [comment]
It seems you are using CUDA 12.9, so you need to install CUDA 12.9 and the corresponding toolkit on your system. After installation, run the following command (which covers almost all GPU architectures) to compile xformers from source:

TORCH_CUDA_ARCH_LIST="6.0;6.1;6.2;7.0;7.2;7.5;8.0;8.6;9.0;10.0;12.0"  
pip install ninja && pip install -v -U git+https://github.com/facebookresearch/xformers.git@main#egg=xformers --no-build-isolation

**Comment by KohakuBlueleaf** [comment]
> It seems you are using CUDA 12.9, so you need to install CUDA 12.9 and the corresponding toolkit on your system. After installation, run the following command (which covers almost all GPU architectures) to compile xformers from source:
> 
> TORCH_CUDA_ARCH_LIST="6.0;6.1;6.2;7.0;7.2;7.5;8.0;8.6;9.0;10.0;12.0" pip install ninja && pip install -v -U git+https://github.com/facebookresearch/xformers.git@main#egg=xformers --no-build-isolation

1. I'm using 50-series GPU and when I using TORCH_CUDA_ARCH_LIST="12.0" it cannot compile at all, the nvcc version is 12.9, and compile from source result in compile error. This situation begin from 0.0.31 but 0.0.31 prebuilt wheel is working so I ignore it.
2. As my statement, IF, pre-built wheel is not intended to use on some situation, there should be some fallback or warning.

**Comment by datasone** [comment]
It's because the build check in `xformers` incorrectly enables FA3 for Blackwell, while FA3 only supports GA100/sm80 and Hopper/sm90.

The invalid argument is triggered by setting an unsupported shared memory size, I think due to limited shared memory size in customer cards (RTX Blackwell/sm120).

I've found a PR #1262 resolving this issue, which hasn't been merged yet.

For a temporary workaround, I changed line 19 in `xformers/ops/fmha/dispatch.py`, setting `_USE_FLASH_ATTENTION_3` to `False` (changing the file in the `site-packages` directory is enough, no need to rebuild).

**Comment by berhil06** [comment]
same probleme with my RTX 5070 cu129-torch2.8.0

**Comment by LSDJesus** [comment]
# The Definitive Guide: How to Compile `xformers` on Windows

This is a step-by-step protocol for successfully compiling `xformers` from source on a modern Windows 10/11 environment. This guide is specifically for users with **Visual Studio 2022**, a **CUDA 12.x** Toolkit, and a modern Python version (3.10+).

---

### **Part I: Prerequisites**

Before starting, ensure your system is correctly configured.

1.  **Visual Studio 2022:**
    *   You must have the **"Desktop development with C++"** workload installed via the Visual Studio Installer.
    *   Within that workload, ensure the **"MSVC v143 VS 2022 C++ x64/x86 build tools"** and the latest **"Windows SDK"** are checked and installed.

2.  **NVIDIA CUDA Toolkit:**
    *   Install the CUDA Toolkit version that corresponds to your PyTorch installation (e.g., for `torch+cu129`, you need CUDA Toolkit 12.9).
    *   Ensure CUDA is correctly added to your system's `PATH` environment variable during installation.

3.  **Python:**
    *   A 64-bit installation of Python 3.10, 3.11, or 3.12.
    *   It is strongly recommended to perform all subsequent steps inside a Python virtual environment (`venv`) to avoid system-wide package conflicts.

4.  **Git for Windows:**
    *   Ensure `git` is installed and accessible from your command line.

---

### **Part II: The Compilation Protocol**

**Step 1: Launch the Correct Developer Command Prompt**

*This is the most critical and frequently missed step.* Do not use a standard Command Prompt or PowerShell, as their build environments are often incomplete.

1.  Open the Windows Start Menu.
2.  Search for **`x64 Native Tools Command Prompt for VS 2022`**.
3.  **Right-click** on the result and select **"Run as administrator"**.

*This special terminal is guaranteed to have the correct paths for the Microsoft C++ compiler, headers, and libraries.*

**Step 2: Prepare the Source Code**

1.  Navigate to your desired build directory (e.g., `cd /d D:\builds`).
2.  Clone the `xformers` repository and enter the new directory:
    ```cmd
    git clone https://github.com/facebookresearch/xformers.git
    cd xformers
    ```
3.  Initialize all the necessary submodules:
    ```cmd
    git submodule update --init --recursive
    ```

**Step 3: Activate Your Python Environment**

1.  Activate the specific `venv` where you have PyTorch installed:
    ```cmd
    D:\path\to\your\venv\scripts\activate
    ```

**Step 4: Modify `setup.py` for Correct Python Tagging (IMPORTANT)**

The default `setup.py` may contain a hardcoded Python version that will cause the build to fail if it doesn't match your system.

1.  Open the `setup.py` file (located in the root of the `xformers` directory) in a text editor.
2.  Scroll to the very bottom to find the `setuptools.setup()` function call.
3.  Locate the `options` argument, which looks like this:
    `options={"bdist_wheel": {"py_limited_api": "cp39"}},`
4.  **Change the `cp39` tag** to match the version of Python in your `venv`.
    *   For Python 3.12, change the line to: `options={"bdist_wheel": {"py_limited_api": "cp312"}},`
    *   For Python 3.11, change it to `cp311`.
    *   For Python 3.10, change it to `cp310`.
5.  Save and close the file.

**Step 5: Set Build Environment Variables**

Run these commands in the Native Tools Command Prompt to configure the build.

1.  Force the build system to use the already configured environment:
    ```cmd
    set DISTUTILS_USE_SDK=1
    ```
2.  Specify which GPU architectures the wheel should be built for (use a semicolon separator):
    ```cmd
    set TORCH_CUDA_ARCH_LIST=8.6;9.0
    ```
    *   **Common Architectures:**
        *   RTX 30-series (Ampere): `8.6`
        *   RTX 40-series (Ada): `8.9`
        *   RTX 50-series (Blackwell): `12.0` *(or the relevant number for future hardware)*
    *   You can include multiple architectures if you have different cards.

**Step 6: Build the Wheel**

Execute the build command. This is a lengthy process.
```cmd
python -m build --wheel --no-isolation
```
A successful build will place your new wheel file in a newly created `dist` folder.

**Step 7: Install Your Custom Wheel**

Use `pip` or your preferred package manager to install the file that was just created.
```cmd
pip install dist\xformers-0.0.33...[rest_of_filename].whl
```

---

### **Part III: Common Issues & Solutions**

- **ISSUE:** The `git submodule update` command fails with **"Filename too long"** errors.
  - **CAUSE:** An old Windows limitation on maximum file path lengths.
  - **SOLUTION:** Open a *standard* Command Prompt as an administrator and run this one-time command to configure Git to handle long paths. Afterwards, delete the corrupted `xformers` directory and start over from Step 2.
    ```cmd
    git config --system core.longpaths true
    ```

- **ISSUE:** The build fails immediately with errors like **`Cannot open include file: 'assert.h'`** or **`'corecrt.h'`**.
  - **CAUSE:** You are not using the correct developer command prompt.
  - **SOLUTION:** You MUST follow **Step 1** precisely. This error indicates that the compiler cannot find the essential C++ standard library files, which is a problem solved by using the **"x64 Native Tools Command Prompt for VS 2022"**.
