### ISSUE TITLE
Batch size >= 65536 in xformers.ops.memory_efficient_attention gives CUDA error.

### ISSUE THREAD

**Issue by comfyanonymous** [facebookresearch/xformers#845]
# 🐛 Bug

Xformers gives a CUDA error like this when the batch size is larger or equal to 65536.
```
RuntimeError: CUDA error: invalid configuration argument
CUDA kernel errors might be asynchronously reported at some other API call, so the stacktrace below might be incorrect.
For debugging consider passing CUDA_LAUNCH_BLOCKING=1.
Compile with `TORCH_USE_CUDA_DSA` to enable device-side assertions.
````

## To Reproduce

```
import xformers
import xformers.ops
import torch

q = torch.zeros(([65536, 16, 80])).cuda()
k = torch.zeros(([65536, 16, 80])).cuda()
v = torch.zeros(([65536, 16, 80])).cuda()
out = xformers.ops.memory_efficient_attention(q, k, v, attn_bias=None)

```

## Expected behavior

Raise a NotImplementedError or a ValueError if the input sizes are not supported.

## Environment

I can reproduce this with the above code on my 3090 TI with xformers 0.0.21 and on the T4 GPU on free google colab with xformers-0.0.22.dev599

**Comment by continue-revolution** [comment]
Can confirm this happens to me as well (AnimateDiff) for xformers >= 0.0.21

If I run with xformers==0.0.20, things work well

**Comment by Yard1** [comment]
Also running into this issue.

**Comment by xzqjack** [comment]
same error

**Comment by samiede** [comment]
I do have the same issue as well!

**Comment by dianyo** [comment]
Hi @danthe3rd ,

I've traced back a bit to cuda code [here](https://github.com/facebookresearch/xformers/blob/v0.0.23/xformers/csrc/attention/cuda/fmha/attention_forward_generic.cu). I found the problem is came from that the batch size used in the original attention layer will build corresponding SM threads on GPU. If the threads(batch) size is larger than one GPU can support (A100 can only support up to 32 x 2048 = 65536 threads), the error occurred.

Also took a quick look at pytorch source code and found that they always have a constraint constant (one called`MAX_BLOCK_SIZE`) to deal with large amount of resource. Using the similar logic might solve this issue.

**Comment by Ir1d** [comment]
Hi, what is the workaround for this issue?

**Comment by guolinke** [comment]
A fast work-around is using several small sub-batches, each with batch size < 6.5k.
